workflows:
  ios-release:
    name: iOS Release
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Codemagic

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Set up signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files com.claudetarrell.bonbonradio --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Flutter clean
        script: |
          flutter clean
          flutter pub get

      - name: Reset CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod repo update
          pod install
          cd ..

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign

      - name: Build IPA
        script: |
          xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true